services:
  design-server:
    image: nginx:alpine
    container_name: design-server
    ports:
      - "3008:80"
    volumes:
      - ./design:/usr/share/nginx/html/design:ro

  web-server:
    image: nginx:alpine
    container_name: web-server
    ports:
      - "8000:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
